### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by taz-man** [Panda88CO/udi-TeslaEV#1]
I am having trouble with token authorization. I'm unsure if there is supposed to be a user name field entered or if it is just I can no get the node server restarted before the 30 second token runs out.

**Comment by Panda88CO** [comment]
no login credentials are supposed to be needed.
in my case the token seem to last longer than 30sec

Christian Olgaard
________________________________
From: taz-man ***@***.***>
Sent: Saturday, May 14, 2022 3:01:01 PM
To: Panda88CO/udi-TeslaEV ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Panda88CO/udi-TeslaEV] Setup (Issue #1)


I am having trouble with token authorization. I'm unsure if there is supposed to be a user name field entered or if it is just I can no get the node server restarted before the 30 second token runs out.

**Comment by taz-man** [comment]
I tried a couple of more times and I think I got the token to be accepted. In the AC it shows Number of EV's 1 but Connected to Tesla Cloud False. PG3 has NS log has error 2022-05-14 16:08:30,102 Thread-4   udi_interface      ERROR    TeslaEVController:createNodes: Exception Controller start: 'NoneType' object is not subscriptable

**Comment by Panda88CO** [comment]
Can you send me the log - IT normally happens when data is corrupt

**Comment by Panda88CO** [comment]
How to generate your own tokens. | TeslascopeThis is what I used Sent from Mail for Windows From: taz-manSent: Saturday, May 14, 2022 4:17 PMTo: Panda88CO/udi-TeslaEVCc: Panda88CO; CommentSubject: Re: [Panda88CO/udi-TeslaEV] Setup (Issue #1) I tried a couple of more times and I think I got the token to be accepted. In the AC it shows Number of EV's 1 but Connected to Tesla Cloud False. PG3 has NS log has error 2022-05-14 16:08:30,102 Thread-4 udi_interface ERROR TeslaEVController:createNodes: Exception Controller start: 'NoneType' object is not subscriptable—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by taz-man** [comment]
[TeslaEV_5-14-2022_80605_PM.zip](https://github.com/Panda88CO/udi-TeslaEV/files/8694228/TeslaEV_5-14-2022_80605_PM.zip)
Thank you for the help I deleted and reinstalled since you mentioned the corrupt data but it still won't connect to the Tesla cloud.

**Comment by Panda88CO** [comment]
It looks like it is logged in, but it gets a timeout [408] after it retrieves the car id (1493027962344560) and tries to retrieve the car info  - not sure if anything has changed  - I’ll need to look at it next week – if I can get access to a car (I do not have a tesla anymore)  Sent from Mail for Windows From: taz-manSent: Saturday, May 14, 2022 8:14 PMTo: Panda88CO/udi-TeslaEVCc: Panda88CO; CommentSubject: Re: [Panda88CO/udi-TeslaEV] Setup (Issue #1) TeslaEV_5-14-2022_80605_PM.zipThank you for the help I deleted and reinstalled since you mentioned the corrupt data but it still won't connect to the Tesla cloud.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by taz-man** [comment]
Ok let me know if there is anything I can do to help.

**Comment by Panda88CO** [comment]
I’ll check if the car I used to have access to still works Sent from Mail for Windows From: taz-manSent: Saturday, May 14, 2022 8:59 PMTo: Panda88CO/udi-TeslaEVCc: Panda88CO; CommentSubject: Re: [Panda88CO/udi-TeslaEV] Setup (Issue #1) Ok let me know if there is anything I can do to help.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by Panda88CO** [comment]
I have an idea what is happening – I am most likely not waiting long enough for the car to wake up before sending next command – I’ll do some changes next week to see if that is it – [408] is likely a result of the car not being fully awake when I try to gather the data?BTW – dis you name your car?  It could be another issue – I do not know how the API handles a car with no name – I use it in naming the nodes  Sent from Mail for Windows From: taz-manSent: Saturday, May 14, 2022 8:59 PMTo: Panda88CO/udi-TeslaEVCc: Panda88CO; CommentSubject: Re: [Panda88CO/udi-TeslaEV] Setup (Issue #1) Ok let me know if there is anything I can do to help.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by taz-man** [comment]
Thank you for the information it is connected now. I did not have my car named, once I did that it still did not connect when I restarted I then woke the car up with the app and restarted then it connected.

**Comment by Panda88CO** [comment]
sounds good.  i know what to fix then.  should be fairly simple fix.   i guess i have never tested with car not connected to charger (i got the credentials from a user so i did not control the test scenarios)

Christian Olgaard
________________________________

**Comment by Panda88CO** [comment]
Hi Is there a chance I could “borrow” a refresh token for your car – I can then fix the code – it is a little difficult when I do not get to see the actual response from the API Alternative is I need to add detailed logging  and we need to fix one by one step (which is not efficient)  Sent from Mail for Windows From: taz-manSent: Saturday, May 14, 2022 8:59 PMTo: Panda88CO/udi-TeslaEVCc: Panda88CO; CommentSubject: Re: [Panda88CO/udi-TeslaEV] Setup (Issue #1) Ok let me know if there is anything I can do to help.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by taz-man** [comment]
I guess you can use the refresh token that I think is in the log I posted since I have not changed it yet. I would feel better if we could do this information exchange through email instead of posting it on here tazzmannaz at gmail.com I have noticed things do not update unless I hit the Update System Data button in the AC.

**Comment by Panda88CO** [comment]
I got the token from the log and it works – however, your car is online now, so  I cannot check the code easily – I think it is fixed but cannot check until car goes to sleep  Which button is it that does not work ?  I assume you are referring to the update under charging node?  Is that correct   Sent from Mail for Windows From: taz-manSent: Monday, May 16, 2022 1:51 PMTo: Panda88CO/udi-TeslaEVCc: Panda88CO; CommentSubject: Re: [Panda88CO/udi-TeslaEV] Setup (Issue #1) I guess you can use the refresh token that I think is in the log I posted since I have not changed it yet. I would feel better if we could do this information exchange through email instead of posting it on here tazzmannaz at gmail.com I have noticed things do not update unless I hit the Update System Data button in the AC.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by taz-man** [comment]
The car was charging a little but has been done for over 30 minutes. I'm not saying the button does not work I am saying the values like % charged or if the charge port is open do not update until I press the button to force the update.

**Comment by Panda88CO** [comment]
OK – let me take a look – it should update with the longPoll setting Sent from Mail for Windows From: taz-manSent: Monday, May 16, 2022 3:58 PMTo: Panda88CO/udi-TeslaEVCc: Panda88CO; CommentSubject: Re: [Panda88CO/udi-TeslaEV] Setup (Issue #1) The car was charging a little but has been done for over 30 minutes. I'm not saying the button does not work I am saying the values like % charged or if the charge port is open do not update until I press the button to force the update.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by Panda88CO** [comment]
Made a new version in Beta – can you give it a try I found the reason for no updates – not all parameters expected existed in your set up – I am not testing if they exist before assigning  - It is not easy when the api is not well documented   Sent from Mail for Windows From: taz-manSent: Monday, May 16, 2022 3:58 PMTo: Panda88CO/udi-TeslaEVCc: Panda88CO; CommentSubject: Re: [Panda88CO/udi-TeslaEV] Setup (Issue #1) The car was charging a little but has been done for over 30 minutes. I'm not saying the button does not work I am saying the values like % charged or if the charge port is open do not update until I press the button to force the update.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by DaneWeintraub** [comment]
I installed and paid for udiTeslaEV2.  I followed the instructions and on the iPhone app but Tesla still needed me to go on my PC and give "my.isy.io" access. Then I redid the instructions and it added the it to my car's KEY.  I checked on the car's screen and I see it with my other KEYs.  I then restated Polyglot and then clicked Authenticate but I keep getting the message, "Please initiate authentication". 

I used the AUTH app but do not know there to put the token.
I clicked the Authenticate button and logged in.
but now it will not let me do it again. i get "Not connected to server... Try refreshing the page.  This will disappear once the connection is re-established." then it disappears and  "Please initiate authentication" comes back.

[udiTeslaEV2_11-8-2024_122717-PM.zip](https://github.com/user-attachments/files/17682261/udiTeslaEV2_11-8-2024_122717-PM.zip)

**Comment by Panda88CO** [comment]
When you click on authenticate in the node server  browser window does it bring you to the tesla site to log in?

Did you go to https://tesla.com/_ak/my.isy.io on your mobile phone's browser?  It should launch the tesla mobile app - I have not heard people  having to go to the PC to do this - It is kind of independent from the node server as this is only to be able to send commands to the EV

One thing you can try it to log out of tesla site account and log back in 

Can you try to enable debug under log and generate a new log - it has a lot more information to help debug

**Comment by DaneWeintraub** [comment]
[udiTeslaEV2_11-8-2024_15219-PM.zip](https://github.com/user-attachments/files/17682936/udiTeslaEV2_11-8-2024_15219-PM.zip)
[udiTeslaEV2_11-8-2024_15219-PM.zip](https://github.com/user-attachments/files/17682938/udiTeslaEV2_11-8-2024_15219-PM.zip)
I did do that link from my iPhone but I had to log in to Tesla to click on giving access (i checked-off all the boxes) then it worked and added the card-key to my car.
I changed the log to debug and tried to do the Authenticate.  See attached.
Also the token is have 5 hours left.  What was I superposed to do with the token string?
Thank you

**Comment by Panda88CO** [comment]
Are you pressing this Authenticate button here 
![image](https://github.com/user-attachments/assets/9408b303-7e2c-4258-9103-314b0ff95336)
It does not look like it is triggering from the log
You do not need to manipulate the token anymore - Node should take care of it

**Comment by DaneWeintraub** [comment]
I did but will not let me do it again. i get "Not connected to server... Try refreshing the page. This will disappear once the connection is re-established." then it disappears and "Please initiate authentication" comes back.

I deleted the and installed again.  SAME

FYI: I see an "update" button on your that I do not have.

[udiTeslaEV2_11-8-2024_23808-PM.zip](https://github.com/user-attachments/files/17683295/udiTeslaEV2_11-8-2024_23808-PM.zip)

**Comment by Panda88CO** [comment]
You are showing version 0.1.38 - correct? 
Are you running the latest version - did you do a system upgrade?  It almost looks to me like you do not have OAUTh installed (part of the firmware) -It seems to me it is an OAUTH issue that is handled by PG3

This is what my system looks like 
![image](https://github.com/user-attachments/assets/7fde88f1-98f8-49c9-8c8e-72f3188caf73)


Maybe try to delete node and install again in a different slot

**Comment by DaneWeintraub** [comment]
I did the upgrade and now my ISY is not working.  It went from version 5.5.4 to 5.8.4
My PG3 is at version 3.1.23
I created a ticket with them.  I'll come back to this once my ISY is back up. Thanks.

**Comment by Panda88CO** [comment]
try rebooting a few times.  i had similar issues in the past.  it eventually recoversChristian OlgaardSent and "auto corrected" by my iPhoneOn Nov 9, 2024, at 07:03, Dane ***@***.***> wrote:﻿
I did the upgrade and now my ISY is not working.  It went from version 5.5.4 to 5.8.4
I created a ticket with them.  I'll come back to this once my ISY is back up. Thanks.

**Comment by DaneWeintraub** [comment]
Universal Devices help me.  
They updated my IoX and PG3x and reinstalled all my plugins.
All is working now.
Thank you

**Comment by Panda88CO** [comment]
good - :-)
